(()=>{const API='https://albushra-community.suyuuutiiii.workers.dev';
const page=(location.pathname.split('/').pop()||'').toLowerCase();
const map={'janazah-support.html':'janazah','transport-support.html':'transport','new-muslim-support.html':'new-muslim','quran-support.html':'quran','practical-care.html':'practical-care','skills-support.html':'skills'};
const service=map[page]||'';
const $=id=>document.getElementById(id),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function selected(name){return [...document.querySelectorAll('input[name="'+name+'"]:checked')].map(x=>x.value)}
function field(id){const x=$(id);return x?x.value.trim():''}
function injectContact(form,prefix,beforeId){if(!form||$(prefix+'ContactValue'))return;const wrap=document.createElement('div');wrap.className='fard-live-contact';wrap.innerHTML='<div class="note" style="margin:4px 0"><strong>Private contact for verified matching</strong><br>This is stored privately for FARD moderation. It is not shown publicly and is released to the matched person only after both sides accept.</div><div class="grid"><input id="'+prefix+'ContactName" maxlength="100" required placeholder="Your name / contact name"><select id="'+prefix+'ContactMethod" required><option value="">Contact method</option><option value="whatsapp">WhatsApp</option><option value="phone">Phone</option><option value="email">Email</option><option value="telegram">Telegram</option><option value="other">Other</option></select></div><input id="'+prefix+'ContactValue" maxlength="180" required placeholder="Private contact detail"><input id="'+prefix+'PreferredLanguage" maxlength="80" placeholder="Preferred language (optional)"><input id="'+prefix+'VerifierName" maxlength="140" placeholder="Verifier / mosque / organisation name (optional)">';const before=$(beforeId);if(before&&before.parentNode===form)form.insertBefore(wrap,before);else form.appendChild(wrap)}
function saveEntry(type,d,serviceKey){localStorage.setItem('fard-entry-'+d.id,JSON.stringify({type,id:d.id,ref_code:d.ref_code,manage_token:d.manage_token,service_key:serviceKey,saved:new Date().toISOString()}))}
function success(msg,d){msg.innerHTML='';const p=document.createElement('span');p.textContent='JazākAllāhu khayran. Received for verification. Reference: '+d.ref_code+'. Your private management key has been saved on this device. ';msg.appendChild(p);const a=document.createElement('a');a.href='fard-status.html';a.textContent='Open My FARD Status →';a.style.fontWeight='900';a.style.color='var(--g,#0b5a3c)';msg.appendChild(a)}
function offline(kind,title,details,msg){localStorage.setItem('fard-draft-'+Date.now(),JSON.stringify({kind,title,details,saved:new Date().toISOString()}));msg.textContent='The live community server is not active yet. Your draft has been saved on this device.'}
async function post(path,payload,msg,form,type,serviceKey,title,details){try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Submission failed');saveEntry(type,d,serviceKey);success(msg,d);form.reset()}catch(e){offline(type,title,details,msg)}}

function wireService(){
 const rf=$('requestForm'),vf=$('volunteerForm');if(!service||!rf||!vf)return false;
 injectContact(rf,'r','rDetails');injectContact(vf,'v','vDetails');
 rf.onsubmit=e=>{e.preventDefault();const title=field('rTitle'),detailsParts=[field('rDetails')];if(field('rFor'))detailsParts.push('Support for: '+field('rFor'));if(field('rMeeting'))detailsParts.push('Hand-off preference: '+field('rMeeting'));if(field('rVerify'))detailsParts.push('Verification route: '+field('rVerify'));const details=detailsParts.filter(Boolean).join(' | ');const payload={service_key:service,title,area:field('rArea'),timing:field('rUrgency'),details,tasks:selected('rTask'),preferred_language:field('rPreferredLanguage'),verifier_name:field('rVerifierName')||field('rVerifier'),contact_name:field('rContactName'),contact_method:field('rContactMethod'),contact_value:field('rContactValue')};post('/api/fard/requests',payload,$('requestMsg'),rf,'request',service,title,details)};
 vf.onsubmit=e=>{e.preventDefault();const st=field('vType'),parts=[field('vDetails')];if(field('vTransport'))parts.push('Transport: '+field('vTransport'));if(field('vVerify'))parts.push('Verification route: '+field('vVerify'));const details=parts.filter(Boolean).join(' | ');const payload={service_key:service,service_type:st,area:field('vArea'),availability:field('vAvail'),languages:field('vLang').split(',').map(x=>x.trim()).filter(Boolean),capabilities:selected('vTask'),details,verifier_name:field('vVerifierName'),contact_name:field('vContactName'),contact_method:field('vContactMethod'),contact_value:field('vContactValue')};post('/api/fard/volunteers',payload,$('volunteerMsg'),vf,'volunteer',service,st,details)};
 return true;
}
function hubServiceFromNeed(v){v=(v||'').toLowerCase();if(v.includes('jan'))return'janazah';if(v.includes('transport'))return'transport';if(v.includes('new muslim'))return'new-muslim';if(v.includes('qur'))return'quran';if(v.includes('skill'))return'skills';if(v.includes('food')||v.includes('access'))return'practical-care';return'general'}
function hubServiceFromOffer(v){v=(v||'').toLowerCase();if(v.includes('jan'))return'janazah';if(v.includes('transport'))return'transport';if(v.includes('mentor'))return'new-muslim';if(v.includes('qur'))return'quran';if(v.includes('elect')||v.includes('plumb')||v.includes('professional')||v.includes('translation'))return'skills';if(v.includes('food')||v.includes('access'))return'practical-care';return'general'}
function wireHub(){const nf=$('needForm'),of=$('offerForm');if(!nf||!of)return;injectContact(nf,'n','needDetails');injectContact(of,'o','offerDetails');
 nf.onsubmit=e=>{e.preventDefault();const sk=hubServiceFromNeed(field('needCat')),title=field('needTitle'),details=(field('needDetails')+' | Verification route: '+field('needVerify')).trim();const payload={service_key:sk,title,area:field('needArea'),timing:field('needWhen'),details,tasks:[field('needCat')],preferred_language:field('nPreferredLanguage'),verifier_name:field('nVerifierName'),contact_name:field('nContactName'),contact_method:field('nContactMethod'),contact_value:field('nContactValue')};post('/api/fard/requests',payload,$('needMsg'),nf,'request',sk,title,details)};
 of.onsubmit=e=>{e.preventDefault();const sk=hubServiceFromOffer(field('offerSkill')),st=field('offerSkill'),details=field('offerDetails');const payload={service_key:sk,service_type:st,area:field('offerArea'),availability:field('offerAvail'),languages:field('offerLang').split(',').map(x=>x.trim()).filter(Boolean),capabilities:[st],details,verifier_name:field('oVerifierName'),contact_name:field('oContactName'),contact_method:field('oContactMethod'),contact_value:field('oContactValue')};post('/api/fard/volunteers',payload,$('offerMsg'),of,'volunteer',sk,st,details)}
}
if(!wireService())wireHub();
})();